language: c
sudo: false
addons:
    apt:
        packages:
        - bc
        - libssl-dev
    artifacts:
        paths:
          - artifacts
env:
    matrix:
    - NERVES_CONFIG=bbb
    - NERVES_CONFIG=rpi_elixir
    - NERVES_CONFIG=rpi2_elixir

script: bash scripts/ci.sh

#branches:
#    only:
#        - master


