defaults: &defaults
  docker:
    - image: nerveshub/docker-build:alpine-3.15.3
  working_directory: ~/repo

run_tests: &run_tests
  run:
    name: Run tests
    command: |
      cd tests && ./run_tests.sh

remote_docker: &remote_docker
  setup_remote_docker:
    version: 20.10.11

docker_env: &docker_env
  run:
    name: Set docker env
    command: |
      REPO=nervesproject/nerves_system_br

      if [ -z "$CIRCLE_TAG" ]; then
        TAG=$CIRCLE_SHA1
      else
        TAG=$(cat VERSION)
      fi

      echo "export DOCKER_REPO=$REPO" >> $BASH_ENV
      echo "export DOCKER_TAG=$TAG" >> $BASH_ENV
      echo "export DOCKER_PATH=support/docker/nerves_system_br" >> $BASH_ENV

docker_build: &docker_build
  run:
    name: Build docker images
    command: |
      apk add --no-cache docker-cli-buildx
      docker context create my_context
      docker buildx create --use my_context
      docker buildx build --platform linux/arm64,linux/amd64 $DOCKER_PATH

docker_save: &docker_save
  run:
    name: Save docker images
    command: |
      mkdir -p /docker
      docker save $DOCKER_REPO:$DOCKER_TAG \
        -o /docker/$DOCKER_TAG.tar

docker_import: &docker_import
  run:
    name: Import docker images
    command: |
      docker load \
        -i /docker/$DOCKER_TAG.tar

docker_push: &docker_push
  run:
    name: Push docker images to dockerhub
    command: |
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

      docker image tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:dev
      docker push $DOCKER_REPO:dev

      if [ -n "$CIRCLE_TAG" ]; then
        docker image tag $DOCKER_REPO:$DOCKER_TAG $DOCKER_REPO:latest
        docker push $DOCKER_REPO:$DOCKER_TAG
        docker push $DOCKER_REPO:latest
      fi

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - <<: *remote_docker
      - <<: *docker_env
      - <<: *docker_build
      - <<: *docker_save
      - save_cache:
          key: docker-{{ .Branch }}-{{ .Revision }}
          paths: "/docker"

  test:
    docker:
      - image: nervesproject/nerves_system_br:dev
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *run_tests

  push:
    <<: *defaults
    steps:
      - checkout
      - <<: *remote_docker
      - <<: *docker_env
      - restore_cache:
          keys:
            - docker-{{ .Branch }}-{{ .Revision }}
      - <<: *docker_import
      - <<: *docker_push

workflows:
  version: 2
  pipeline:
      jobs:
        - build:
            context: org-global
            filters:
              tags:
                only: /.*/
        - push:
            context: org-global
            requires:
              - build
            filters:
              tags:
                only: /.*/
        - test:
            context: org-global
            requires:
              - push
            filters:
              tags:
                only: /.*/
